# Generated by Django 4.2.28 on 2026-03-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('t-shirts', 'T-Shirts'), ('dresses', 'Dresses'), ('jackets', 'Jackets'), ('trousers', 'Trousers'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], max_length=20)),
                ('age_range', models.CharField(choices=[('0-6m', '0-6 Months'), ('6-12m', '6-12 Months'), ('1-2y', '1-2 Years'), ('2-4y', '2-4 Years'), ('5-7y', '5-7 Years'), ('8-10y', '8-10 Years'), ('11-12y', '11-12 Years')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('sizes', models.CharField(help_text='Comma-separated sizes, e.g. "2Y, 3Y, 4Y"', max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
